services:
  comfy-cpu:
    image: ghcr.io/pixeloven/comfyui-docker/comfy-cpu:latest
    user: ${PUID:-1000}:${PGID:-1000}
    container_name: react-extension-dev-cpu
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=--cpu
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      # Mount models and other ComfyUI directories
      - comfyui_data:/data
      - comfyui_output:/output
      # Mount ComfyUI custom_nodes directory
      - ./:/data/config/comfy/custom_nodes/ComfyUI-React-Extension-Template
    stop_signal: SIGKILL
    tty: true

  comfy-nvidia:
    image: ghcr.io/pixeloven/comfyui-docker/comfy-nvidia:latest
    user: ${PUID:-1000}:${PGID:-1000}
    container_name: comfyui-react-extension-dev-nvidia
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      # Mount models and other ComfyUI directories
      - comfyui_data:/data
      - comfyui_output:/output
      # Mount ComfyUI custom_nodes directory
      - ./:/data/config/comfy/custom_nodes/ComfyUI-React-Extension-Template
    stop_signal: SIGKILL
    tty: true
    runtime: nvidia

  # Can the UI run in dev mode outside of the comfy container? (how can we expose the comfyui API)
  # We can still mount the extension into comfy container so the backend has access to the extension
  # But we need to expose the comfyui API to the UI

  # # Development server for React hot reload
  # react-dev:
  #   image: node:18-alpine
  #   container_name: react-extension-dev
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./ui:/app
  #     - /app/node_modules
  #   working_dir: /app
  #   command: >
  #     sh -c "
  #       npm install &&
  #       npm run dev -- --host 0.0.0.0 --port 5173
  #     "
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - comfyui

volumes:
  comfyui_data:
  comfyui_output:
