services:
  comfyui:
    image: ghcr.io/pixeloven/comfyui-docker/comfy-cpu:latest
    user: ${PUID:-1000}:${PGID:-1000}
    container_name: comfy-cpu-dev
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=--cpu
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      # Mount models and other ComfyUI directories
      - comfyui_data:/data/config/comfy/models
      - comfyui_output:/data/config/comfy/output
      # Mount ComfyUI custom_nodes directory
      - ./:/data/config/comfy/custom_nodes/ComfyUI-React-Extension-Template
    command: >
      bash -c "
        # Install Node.js for React development
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get update && apt-get install -y nodejs
        
        # Install extension dependencies and build
        cd /workspace/ComfyUI-React-Extension-Template/ui
        npm install
        npm run build
        
        # Start ComfyUI
        cd /workspace/ComfyUI
        python main.py --listen 0.0.0.0 --port 8188
      "

  comfyui-nvidia:
    image: ghcr.io/pixeloven/comfyui-docker/comfy-nvidia:latest
    container_name: comfyui-dev-nvidia
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=--cpu
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      # Mount models and other ComfyUI directories
      - comfyui_data:/data/config/comfy/models
      - comfyui_output:/data/config/comfy/output
      # Mount ComfyUI custom_nodes directory
      - ./:/data/config/comfy/custom_nodes/ComfyUI-React-Extension-Template
    command: >
      bash -c "
        # Install Node.js for React development
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get update && apt-get install -y nodejs
        
        # Install extension dependencies and build
        cd /workspace/ComfyUI-React-Extension-Template/ui
        npm install
        npm run build
        
        # Start ComfyUI
        cd /workspace/ComfyUI
        python main.py --listen 0.0.0.0 --port 8188
      "

  # Development server for React hot reload
  react-dev:
    image: node:18-alpine
    container_name: react-extension-dev
    profiles:
      - comfy-cpu
      - comfy-nvidia
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 5173
      "
    environment:
      - NODE_ENV=development
    depends_on:
      - comfyui

volumes:
  comfyui_data:
  comfyui_output:
